apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dw-05d-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dw-05d
    server: https://kubernetes.default.svc
  project: dwaas
  source:
    path: overlays/05d
    repoURL: https://github.com/ppetrucz/dw-config
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
